=== hydroshare/hydroshare/hs_core/tests/data/test_resource_metadata_files/model_program/setup_schema.json
{
    "type": "object",
    "title": "MODFLOW Model Instance Metadata Schema",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "properties": {
        "studyArea": {
            "type": "object",
            "title": "Study Area",
            "properties": {
                "totalWidth": {
                    "type": "number",
                    "title": "Total Width (in meters)",
                    "default": 0,
                    "minimum": 0,
                    "description": "Total width of the study area used in creating this model instance.",
                    "propertyOrder": 2
                },
                "totalLength": {
                    "type": "number",
                    "title": "Total Length (in meters)",
                    "default": 0,
                    "minimum": 0,
                    "description": "Total length of the study area used in creating this model instance.",
                    "propertyOrder": 1
                },
                "maximumElevation": {
                    "type": "number",
                    "title": "Maximum Elevation (in meters)",
                    "default": 0,
                    "description": "Maximum elevation of the study area used in creating this model instance.",
                    "propertyOrder": 3
                },
                "minimumElevation": {
                    "type": "number",
                    "title": "Minimum Elevation (in meters)",
                    "default": 0,
                    "description": "Minimum elevation of the study area used in creating this model instance.",
                    "propertyOrder": 4
                }
            },
            "description": "The dimentions of the study area used in creating this model instance.",
            "propertyOrder": 8,
            "additionalProperties": false
        },
        "modelSolver": {
            "enum": [
                "DE4",
                "GMG",
                "LMG",
                "PCG",
                "PCGN",
                "SIP",
                "SOR",
                "NWT"
            ],
            "type": "string",
            "title": "Model Solver",
            "default": "",
            "description": "Model solver used in creating this model instance.",
            "propertyOrder": 5
        },
        "stressPeriod": {
            "type": "object",
            "title": "Stress Periods",
            "properties": {
                "type": {
                    "enum": [
                        "Steady",
                        "Transient",
                        "Steady and Transient"
                    ],
                    "type": "string",
                    "title": "Type",
                    "default": "",
                    "description": "Type of stress period used in creating this model instance.",
                    "propertyOrder": 1
                },
                "lengthOfSteadyStateStressPeriod": {
                    "type": "number",
                    "title": "Length of Steady State Stress Periods",
                    "default": 1,
                    "minimum": 0,
                    "description": "Length of steady state stress periods used in creating this model instance.",
                    "propertyOrder": 2
                },
                "TypeOfTransientStateStressPeriod": {
                    "enum": [
                        "Annually",
                        "Monthly",
                        "Daily",
                        "Hourly",
                        "Other"
                    ],
                    "type": "string",
                    "title": "Type of Transient State Stress Periods",
                    "default": "",
                    "description": "Type of transient state stress periods used in creating this model instance.",
                    "propertyOrder": 1
                },
                "lengthOfTransientStateStressPeriod": {
                    "type": "number",
                    "title": "Length of Transient State Stress Periods",
                    "default": 1,
                    "minimum": 0,
                    "description": "Length of transient state stress periods used in creating this model instance.",
                    "propertyOrder": 4
                }
            },
            "description": "Stress periods used in creating this model instance.",
            "propertyOrder": 10,
            "additionalProperties": false
        },
        "gridDimensions": {
            "type": "object",
            "title": "Grid Dimensions",
            "properties": {
                "typeOfRows": {
                    "enum": [
                        "Regular",
                        "Irregular"
                    ],
                    "type": "string",
                    "title": "Type of Rows",
                    "default": "",
                    "description": "Type of rows used in creating this model instance.",
                    "propertyOrder": 2
                },
                "NumberOfRows": {
                    "type": "number",
                    "title": "Number of Rows",
                    "default": 1,
                    "minimum": 0,
                    "description": "Number of rows used in creating this model instance.",
                    "propertyOrder": 3
                },
                "typeOfColumns": {
                    "enum": [
                        "Regular",
                        "Irregular"
                    ],
                    "type": "string",
                    "title": "Type of Columns",
                    "default": "",
                    "description": "Type of columns used in creating this model instance.",
                    "propertyOrder": 4
                },
                "numberOfLayers": {
                    "type": "number",
                    "title": "Number of Layers",
                    "default": 1,
                    "minimum": 0,
                    "description": "Number of layers used in creating this model instance.",
                    "propertyOrder": 1
                },
                "NumberOfColumns": {
                    "type": "number",
                    "title": "Number of Columns",
                    "default": 1,
                    "minimum": 0,
                    "description": "Number of columns used in creating this model instance.",
                    "propertyOrder": 5
                }
            },
            "description": "Grid dimensions used in creating this model instance.",
            "propertyOrder": 9,
            "additionalProperties": false
        },
        "modelParameter": {
            "type": "string",
            "title": "Model Parameters",
            "default": "",
            "description": "Model parameters used in creating this model instance.",
            "propertyOrder": 4
        },
        "groundwaterFlow": {
            "type": "object",
            "title": "Groundwater Flow",
            "properties": {
                "flowPackage": {
                    "enum": [
                        "BCF6",
                        "LPF",
                        "HUF2",
                        "UPW"
                    ],
                    "type": "string",
                    "title": "Flow Package",
                    "default": "",
                    "description": "Flow package used in creating this model instance.",
                    "propertyOrder": 1
                },
                "flowParameter": {
                    "enum": [
                        "Hydraulic Conductivity",
                        "Transmissivity"
                    ],
                    "type": "string",
                    "title": "Flow Parameter",
                    "default": "",
                    "description": "Flow parameter used in creating this model instance.",
                    "propertyOrder": 5
                },
                "IncludesUnsaturatedZonePackage": {
                    "type": "boolean",
                    "title": "Includes Unsaturated Zone Package (UZF)",
                    "format": "checkbox",
                    "propertyOrder": 2
                },
                "IncludesSeawaterIntrusionPackage": {
                    "type": "boolean",
                    "title": "Includes Seawater Intrusion package (SWI2)",
                    "format": "checkbox",
                    "propertyOrder": 4
                },
                "IncludesHorizontalFlowBarrierPackage": {
                    "type": "boolean",
                    "title": "Includes Horizontal Flow Barrier package (HFB6)",
                    "format": "checkbox",
                    "propertyOrder": 3
                }
            },
            "description": "Groundwater flow used in creating this model instance.",
            "propertyOrder": 11,
            "additionalProperties": false
        },
        "modelCalibration": {
            "type": "object",
            "title": "Model Calibration",
            "properties": {
                "observationType": {
                    "type": "string",
                    "title": "Observation Types",
                    "default": "",
                    "description": "Observation types used in creating this model instance.",
                    "propertyOrder": 2
                },
                "calibrationMethod": {
                    "type": "string",
                    "title": "Calibration Methods",
                    "default": "",
                    "description": "Calibration methods used in creating this model instance.",
                    "propertyOrder": 4
                },
                "calibratedParameter": {
                    "type": "string",
                    "title": "Calibrated Parameters",
                    "default": "",
                    "description": "Calibrated parameters used in creating this model instance.",
                    "propertyOrder": 1
                },
                "observationProcessPackage": {
                    "enum": [
                        "ADV2",
                        "CHOB",
                        "DROB",
                        "DTOB",
                        "GBOB",
                        "HOB",
                        "OBS",
                        "RVOB",
                        "STOB"
                    ],
                    "type": "string",
                    "title": "Observation Process Packages",
                    "default": "",
                    "description": "Type of transient state stress periods used in creating this model instance.",
                    "propertyOrder": 3
                }
            },
            "description": "Model calibration used in creating this model instance.",
            "propertyOrder": 12,
            "additionalProperties": false
        },
        "subsidencePackage": {
            "enum": [
                "IBS",
                "SUB",
                "SWT"
            ],
            "type": "string",
            "title": "Subsidence Package",
            "default": "",
            "description": "Subsidence package used in creating this model instance.",
            "propertyOrder": 7
        },
        "outputControlPackage": {
            "type": "object",
            "title": "Output Control Packages",
            "properties": {
                "OC": {
                    "type": "boolean",
                    "title": "OC",
                    "format": "checkbox",
                    "propertyOrder": 5
                },
                "HYD": {
                    "type": "boolean",
                    "title": "HYD",
                    "format": "checkbox",
                    "propertyOrder": 2
                },
                "GAGE": {
                    "type": "boolean",
                    "title": "GAGE",
                    "format": "checkbox",
                    "propertyOrder": 1
                },
                "LMT6": {
                    "type": "boolean",
                    "title": "LMT6",
                    "format": "checkbox",
                    "propertyOrder": 3
                },
                "MNWI": {
                    "type": "boolean",
                    "title": "MNWI",
                    "format": "checkbox",
                    "propertyOrder": 4
                }
            },
            "description": "Output control packages used in creating this model instance.",
            "propertyOrder": 6,
            "additionalProperties": false
        },
        "specifiedFluxBoundaryPackages": {
            "type": "object",
            "title": "Specified Flux Boundary Packages",
            "properties": {
                "FHB": {
                    "type": "boolean",
                    "title": "FHB",
                    "format": "checkbox",
                    "propertyOrder": 1
                },
                "RCH": {
                    "type": "boolean",
                    "title": "RCH",
                    "format": "checkbox",
                    "propertyOrder": 2
                },
                "WEL": {
                    "type": "boolean",
                    "title": "WEL",
                    "format": "checkbox",
                    "propertyOrder": 3
                },
                "OtherPackages": {
                    "type": "string",
                    "title": "Other packages",
                    "propertyOrder": 4
                }
            },
            "description": "Specified flux boundary packages used in creating this model instance.",
            "propertyOrder": 2,
            "additionalProperties": false
        },
        "specifiedHeadBoundaryPackages": {
            "type": "object",
            "title": "Specified Head Boundary Packages",
            "properties": {
                "BFH": {
                    "type": "boolean",
                    "title": "BFH",
                    "format": "checkbox",
                    "propertyOrder": 1
                },
                "CHD": {
                    "type": "boolean",
                    "title": "CHD",
                    "format": "checkbox",
                    "propertyOrder": 2
                },
                "FHB": {
                    "type": "boolean",
                    "title": "FHB",
                    "format": "checkbox",
                    "propertyOrder": 3
                },
                "OtherPackages": {
                    "type": "string",
                    "title": "Other packages",
                    "propertyOrder": 4
                }
            },
            "description": "Specified head boundary packages used in creating this model instance.",
            "propertyOrder": 1,
            "additionalProperties": false
        },
        "headDependentFluxBoundaryPackages": {
            "type": "object",
            "title": "Head Dependent Flux Boundary Packages",
            "properties": {
                "DAF": {
                    "type": "boolean",
                    "title": "DAF",
                    "format": "checkbox",
                    "propertyOrder": 1
                },
                "DRN": {
                    "type": "boolean",
                    "title": "DRN",
                    "format": "checkbox",
                    "propertyOrder": 3
                },
                "DRT": {
                    "type": "boolean",
                    "title": "DRT",
                    "format": "checkbox",
                    "propertyOrder": 4
                },
                "ETS": {
                    "type": "boolean",
                    "title": "ETS",
                    "format": "checkbox",
                    "propertyOrder": 5
                },
                "EVT": {
                    "type": "boolean",
                    "title": "EVT",
                    "format": "checkbox",
                    "propertyOrder": 6
                },
                "GHB": {
                    "type": "boolean",
                    "title": "GHB",
                    "format": "checkbox",
                    "propertyOrder": 7
                },
                "LAK": {
                    "type": "boolean",
                    "title": "LAK",
                    "format": "checkbox",
                    "propertyOrder": 8
                },
                "RES": {
                    "type": "boolean",
                    "title": "RES",
                    "format": "checkbox",
                    "propertyOrder": 11
                },
                "RIP": {
                    "type": "boolean",
                    "title": "RIP",
                    "format": "checkbox",
                    "propertyOrder": 12
                },
                "RIV": {
                    "type": "boolean",
                    "title": "RIV",
                    "format": "checkbox",
                    "propertyOrder": 13
                },
                "SFR": {
                    "type": "boolean",
                    "title": "SFR",
                    "format": "checkbox",
                    "propertyOrder": 14
                },
                "STR": {
                    "type": "boolean",
                    "title": "STR",
                    "format": "checkbox",
                    "propertyOrder": 15
                },
                "UZF": {
                    "type": "boolean",
                    "title": "UZF",
                    "format": "checkbox",
                    "propertyOrder": 16
                },
                "DAFG": {
                    "type": "boolean",
                    "title": "DAFG",
                    "format": "checkbox",
                    "propertyOrder": 2
                },
                "MNW1": {
                    "type": "boolean",
                    "title": "MNW1",
                    "format": "checkbox",
                    "propertyOrder": 9
                },
                "MNW2": {
                    "type": "boolean",
                    "title": "MNW2",
                    "format": "checkbox",
                    "propertyOrder": 10
                },
                "OtherPackages": {
                    "type": "string",
                    "title": "Other packages",
                    "propertyOrder": 17
                }
            },
            "description": "Head dependent flux boundary packages used in creating this model instance.",
            "propertyOrder": 3,
            "additionalProperties": false
        }
    },
    "description": "A sample schema for MODFLOW model instance metadata.",
    "additionalProperties": false
}

=== hydroshare/hydroshare/hs_core/tests/data/test_resource_metadata_files/model_instance_folder_based/model_instance/model_instance_schema_values.json
{
    "studyArea": {
        "totalWidth": 0,
        "totalLength": 0,
        "maximumElevation": 0,
        "minimumElevation": 0
    },
    "modelSolver": "DE4",
    "stressPeriod": {
        "type": "Steady",
        "lengthOfSteadyStateStressPeriod": 1,
        "TypeOfTransientStateStressPeriod": "Annually",
        "lengthOfTransientStateStressPeriod": 1
    },
    "gridDimensions": {
        "typeOfRows": "Regular",
        "NumberOfRows": 1,
        "typeOfColumns": "Regular",
        "numberOfLayers": 1,
        "NumberOfColumns": 1
    },
    "modelParameter": "",
    "groundwaterFlow": {
        "flowPackage": "BCF6",
        "flowParameter": "Hydraulic Conductivity",
        "IncludesUnsaturatedZonePackage": false,
        "IncludesSeawaterIntrusionPackage": false,
        "IncludesHorizontalFlowBarrierPackage": false
    },
    "modelCalibration": {
        "observationType": "",
        "calibrationMethod": "",
        "calibratedParameter": "",
        "observationProcessPackage": "ADV2"
    },
    "subsidencePackage": "IBS",
    "outputControlPackage": {
        "OC": false,
        "HYD": false,
        "GAGE": true,
        "LMT6": false,
        "MNWI": true
    },
    "specifiedFluxBoundaryPackages": {
        "FHB": true,
        "RCH": true,
        "WEL": false,
        "OtherPackages": ""
    },
    "specifiedHeadBoundaryPackages": {
        "BFH": false,
        "CHD": false,
        "FHB": false,
        "OtherPackages": ""
    },
    "headDependentFluxBoundaryPackages": {
        "DAF": false,
        "DRN": true,
        "DRT": false,
        "ETS": true,
        "EVT": false,
        "GHB": false,
        "LAK": false,
        "RES": false,
        "RIP": false,
        "RIV": false,
        "SFR": false,
        "STR": true,
        "UZF": false,
        "DAFG": false,
        "MNW1": false,
        "MNW2": false,
        "OtherPackages": ""
    }
}

=== hydroshare/hydroshare/hs_core/tests/data/test_resource_metadata_files/model_instance_folder/generic_file_schema_values.json
{
    "studyArea": {
        "totalWidth": 1,
        "totalLength": 2,
        "maximumElevation": 3,
        "minimumElevation": 4
    },
    "modelSolver": "DE4",
    "stressPeriod": {
        "type": "Steady",
        "lengthOfSteadyStateStressPeriod": 1,
        "TypeOfTransientStateStressPeriod": "Annually",
        "lengthOfTransientStateStressPeriod": 1
    },
    "gridDimensions": {
        "typeOfRows": "Regular",
        "NumberOfRows": 1,
        "typeOfColumns": "Regular",
        "numberOfLayers": 1,
        "NumberOfColumns": 1
    },
    "modelParameter": "qwer",
    "groundwaterFlow": {
        "flowPackage": "BCF6",
        "flowParameter": "Hydraulic Conductivity",
        "IncludesUnsaturatedZonePackage": false,
        "IncludesSeawaterIntrusionPackage": false,
        "IncludesHorizontalFlowBarrierPackage": true
    },
    "modelCalibration": {
        "observationType": "observed",
        "calibrationMethod": "method",
        "calibratedParameter": "calibrated",
        "observationProcessPackage": "ADV2"
    },
    "subsidencePackage": "IBS",
    "outputControlPackage": {
        "OC": false,
        "HYD": false,
        "GAGE": true,
        "LMT6": false,
        "MNWI": false
    },
    "specifiedFluxBoundaryPackages": {
        "FHB": false,
        "RCH": true,
        "WEL": false,
        "OtherPackages": "asdf"
    },
    "specifiedHeadBoundaryPackages": {
        "BFH": true,
        "CHD": false,
        "FHB": false,
        "OtherPackages": ""
    },
    "headDependentFluxBoundaryPackages": {
        "DAF": true,
        "DRN": false,
        "DRT": false,
        "ETS": false,
        "EVT": false,
        "GHB": true,
        "LAK": false,
        "RES": false,
        "RIP": false,
        "RIV": false,
        "SFR": false,
        "STR": false,
        "UZF": false,
        "DAFG": false,
        "MNW1": false,
        "MNW2": false,
        "OtherPackages": "fds"
    }
}
